### ISSUE TITLE
UI Functionality Improvement 

### ISSUE THREAD

**Issue by Minnowo** [EZCampusDevs/frontend#20]
After adding a course in the ICS page, you should remove the course from the search results until it is removed from the selected courses.

The button already prevents adding it twice.

**Comment by jasonmzx** [comment]
I've added it so when you add courses, the button disappears, and you get an Added Text instead, I initially added Delete upon saved, but was having some major issues with the Scroll, since it's implemented in a way where 5 elements need to be rendered to actually scroll more, so the deletion of entries where acting weird...

![image](https://github.com/EZCampusDevs/frontend/assets/68576119/97643b9a-92c7-42e1-842c-e0f5d2eb90dc)

Currently have this...

If you don't like this, We could include the elements and set them to Invisible, this way scroll will still work whilst simulating a "deletion" upon save
