### ISSUE TITLE
BUG: Calendar Creation Seemingly Bugged For Spring/Summer

### ISSUE THREAD

**Issue by buthed010203** [EZCampusDevs/frontend#9]
Worked great during fall and winter sems, tried it for the spring semester a couple months back with no luck. Tried it again now for the summer one and it's still not functional. I know this isn't the right repo but I can't be bothered to locate the correct one.
<img width="897" alt="image" src="https://github.com/EZCampusDevs/frontend/assets/26940575/b91ca307-122c-4486-8870-70334f3e576b">

**Edit:** It would appear that it only breaks *most* of the time, adding one on its own can sometimes work for whatever reason. 
<img width="889" alt="image" src="https://github.com/EZCampusDevs/frontend/assets/26940575/c3a30d1c-fc97-4494-8cbb-9d0be8a294c6">

Also, selecting the institution is scuffed, it has to be done twice otherwise the state doesn't update for whatever reason.
<img width="900" alt="image" src="https://github.com/EZCampusDevs/frontend/assets/26940575/8dd31f08-bc1e-4a63-843b-2c50d41fa629">

**Comment by buthed010203** [comment]
Come to think of it... these issues are probably related. It seems that selecting the term twice does actually make it work so theres probably just some fun state bug to work out.

**Comment by jasonmzx** [comment]
Hello @buthed010203, We're currently revamping this entire page but this unknown course code issue `PHY1020U` thing, is a great catch, thank you we'll look into it.

**Comment by danielljeon** [comment]
Hi @buthed010203, sorry for the late reply. We normally don't get our users checking out our repos and opening issues 😅. 

That build was deprecated a while back. The backend connection to our database was disabled and a large part of the backend was being rewritten at the time. We've since moved to our new build [https://ezcampus.org](https://ezcampus.org), which is still actively under development.

Since this pertains to our old build I will close this issue now. Thanks for letting us know! We'll definitely be keeping a closer eye on the repo issues going forward.

**Comment by buthed010203** [comment]
Was referring to the website that you linked btw

**Comment by buthed010203** [comment]
Ah wait no that was the .ca tld mb

**Comment by danielljeon** [comment]
No worries. We've set up redirects to the `.org` domain without much notice to users which is admittedly confusing.
